#ifndef SETUP_PAGE_H
#define SETUP_PAGE_H

static const char SETUP_HTML_PAGE[] = 
"<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1.0'>"
"<title>BLE Satellite</title><style>body{font-family:Arial,sans-serif;background:#667eea;padding:20px;margin:0}"
".box{background:#fff;max-width:450px;margin:20px auto;padding:25px;border-radius:10px;box-shadow:0 4px 20px rgba(0,0,0,0.2)}"
"h1{margin:0 0 10px;font-size:24px}h2{margin:20px 0 10px;font-size:18px;color:#667eea;border-bottom:2px solid #667eea;padding-bottom:5px}"
"input{width:100%;padding:10px;margin:8px 0;border:1px solid #ddd;border-radius:5px;box-sizing:border-box}"
"button{width:100%;padding:12px;background:#667eea;color:#fff;border:none;border-radius:5px;font-size:16px;cursor:pointer;margin-top:10px}"
"button:hover{background:#5568d3}.msg{margin-top:15px;padding:10px;border-radius:5px;display:none}"
".ok{background:#4caf50;color:#fff;display:block}.err{background:#f44336;color:#fff;display:block}"
"label{display:block;margin:10px 0 5px;font-weight:bold}.note{font-size:12px;color:#666;margin-top:5px}"
".status{background:#f5f5f5;padding:15px;border-radius:5px;margin:10px 0}.stat-row{display:flex;justify-content:space-between;margin:5px 0}"
".stat-label{color:#666;font-size:14px}.stat-value{font-weight:bold;color:#333}.stat-ok{color:#4caf50}.stat-err{color:#f44336}"
".form-section{margin:20px 0;padding:15px;background:#f9f9f9;border-radius:5px}"
"</style></head><body><div class='box'><h1>🛰️ BLE Satellite</h1>"
"<div class='status' id='status'><div class='stat-row'><span class='stat-label'>WiFi:</span><span class='stat-value' id='wifi-status'>...</span></div>"
"<div class='stat-row'><span class='stat-label'>Gateway:</span><span class='stat-value' id='gw-status'>...</span></div>"
"<div class='stat-row'><span class='stat-label'>BLE Devices:</span><span class='stat-value' id='ble-count'>...</span></div></div>"
"<h2>⚙️ Configuration</h2>"
"<div class='form-section'><h3 style='margin:10px 0 5px;font-size:16px'>📡 WiFi Network</h3>"
"<form id='wf'><input id='s' placeholder='WiFi SSID' required><input id='p' type='password' placeholder='Password'>"
"<button type='submit'>Save WiFi & Connect</button></form><div class='msg' id='wm'></div></div>"
"<div class='form-section'><h3 style='margin:10px 0 5px;font-size:16px'>🛰️ Satellite Mode</h3>"
"<form id='gf'><label><input type='checkbox' id='sat'> Forward BLE data to Gateway</label>"
"<input id='gwip' placeholder='Gateway IP (e.g. 192.168.1.100)'>"
"<div class='note'>All BLE devices sent automatically</div>"
"<button type='submit'>Save Gateway Settings</button></form><div class='msg' id='gm'></div></div></div><script>"
"async function updateStatus(){try{const r=await fetch('/api/status');const d=await r.json();"
"document.getElementById('wifi-status').innerHTML=d.wifi_connected?`<span class='stat-ok'>✓ ${d.wifi_ssid}</span>`:'<span class='stat-err'>Not connected</span>';"
"document.getElementById('s').value=d.wifi_ssid||'';"
"document.getElementById('gw-status').innerHTML=d.satellite_mode?`<span class='stat-ok'>→ ${d.gateway_ip}</span>`:'<span class='stat-err'>Disabled</span>';"
"document.getElementById('sat').checked=d.satellite_mode;document.getElementById('gwip').value=d.gateway_ip||'';"
"document.getElementById('ble-count').textContent=d.ble_devices+' found';}catch(e){}}"
"setInterval(updateStatus,2000);updateStatus();"
"document.getElementById('wf').onsubmit=async(e)=>{e.preventDefault();const s=document.getElementById('s').value,p=document.getElementById('p').value,"
"m=document.getElementById('wm');try{const r=await fetch('/api/wifi',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ssid:s,password:p})});const d=await r.json();if(d.ok){m.className='msg ok';m.textContent='✓ WiFi saved! Connecting...';"
"setTimeout(()=>{m.style.display='none';updateStatus()},3000)}"
"else{m.className='msg err';m.textContent='✗ '+(d.error||'Error')}}catch(e){m.className='msg err';m.textContent='✗ Connection error'}};"
"document.getElementById('gf').onsubmit=async(e)=>{e.preventDefault();const sat=document.getElementById('sat').checked,gw=document.getElementById('gwip').value,"
"m=document.getElementById('gm');try{const r=await fetch('/api/gateway',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({satellite:sat,gateway_ip:gw})});const d=await r.json();if(d.ok){m.className='msg ok';"
"m.textContent='✓ Gateway settings saved!';setTimeout(()=>{m.style.display='none';updateStatus()},3000)}"
"else{m.className='msg err';m.textContent='✗ '+(d.error||'Error')}}catch(e){m.className='msg err';m.textContent='✗ Connection error'}}"
"</script></body></html>";

#endif // SETUP_PAGE_H

